<div class="jumbotron">

    <p><a class="btn btn-success pull-right" href="<?php  echo $this->url('home'); ?>" >Acceil</a></p>


    <?php

    foreach ($student as $one )
    {?>

        <p>nom:  <?php  echo  $one->getNom();?></p>
        <p>prenom:  <?php  echo  $one->getPrenom();?></p>
        <p>nationalite: <?php  echo  $one->getPrenom();?></p>
        <p>mail:<?php  echo  $one->getMail();?></p>

        <p>situation:  <?php  echo  $one->getSituation();?></p>
        <p>date de naissance:<?php  echo  $one->getDateNaissance()->format('d-m-y');?></p>

        <p><?php  echo  $one->getRemarques();?></p>
        <p><?php $trainings= $one->getTrainings();
            foreach ($trainings as $training)
            {
               echo  'hh'.$training->getTitle().'<br>';

            }



            ;?></p>




    <?php };?>

    <!--    <p><a class="btn btn-success btn-lg" href="https://github.com/zendframework/zendframework" target="_blank">Fork Zend Framework on GitHub &raquo;</a></p>-->
</div>


<!---->
<!--        <p><a class="btn btn-success btn-lg" href="https://github.com/zendframework/zendframework" target="_blank">Fork Zend Framework on GitHub &raquo;</a></p>-->-->
<!--</div>-->