<div>
    Number of students:<?php echo $nbr; ?><br><br>
    Duration :<?php echo $duration; ?><br><br>
    start date:<?php echo $startd->format('d/m/y'); ?><br><br>
    End date: <?php echo $endd->format('d/m/y'); ?><br><br>
    état:<br><br>
<?php    echo $this->TrainingHelper()->getstatus($startd,$endd);?>

    <!--    <p><a class="btn btn-success pull-right" href="/second" target="_blank">next</a></p>-->

</div>
